FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY control-plane/ .
RUN go mod tidy
RUN go build -o control-plane ./cmd/server/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/control-plane .
CMD ["./control-plane"]
