// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/hydra.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HydraServiceClient is the client API for HydraService service.
type HydraServiceClient interface {
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (HydraService_StreamLogsClient, error)
}

type hydraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHydraServiceClient(cc grpc.ClientConnInterface) HydraServiceClient {
	return &hydraServiceClient{cc}
}

func (c *hydraServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, "/hydra.HydraService/SubmitJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hydraServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, "/hydra.HydraService/GetJobStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hydraServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (HydraService_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HydraService_serviceDesc.Streams[0], "/hydra.HydraService/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &hydraServiceStreamLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HydraService_StreamLogsClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type hydraServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *hydraServiceStreamLogsClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HydraServiceServer is the server API for HydraService service.
// All implementations must embed UnimplementedHydraServiceServer
// for forward compatibility
type HydraServiceServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	StreamLogs(*StreamLogsRequest, HydraService_StreamLogsServer) error
	mustEmbedUnimplementedHydraServiceServer()
}

type UnimplementedHydraServiceServer struct {
}

func (UnimplementedHydraServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedHydraServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedHydraServiceServer) StreamLogs(*StreamLogsRequest, HydraService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedHydraServiceServer) mustEmbedUnimplementedHydraServiceServer() {}

func RegisterHydraServiceServer(s grpc.ServiceRegistrar, srv HydraServiceServer) {
	s.RegisterService(&_HydraService_serviceDesc, srv)
}

func _HydraService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HydraServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hydra.HydraService/SubmitJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HydraServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HydraService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HydraServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hydra.HydraService/GetJobStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HydraServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HydraService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HydraServiceServer).StreamLogs(m, &hydraServiceStreamLogsServer{stream})
}

type HydraService_StreamLogsServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type hydraServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *hydraServiceStreamLogsServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

var _HydraService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hydra.HydraService",
	HandlerType: (*HydraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _HydraService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _HydraService_GetJobStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _HydraService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/hydra.proto",
}
